{
    "compute_environment": "LOCAL_MACHINE",
    "distributed_type": "DEEPSPEED",
    "downcast_bf16": false,
    "machine_rank": 0,
    "main_training_function": "main",
    "mixed_precision": "no",
    "num_machines": 1,
    "num_processes": 2,
    "deepspeed_config": {
        "train_batch_size": "auto",
        "gradient_accumulation_steps": 1,
        "zero_allow_untested_optimizer": true,
        "zero_optimization": {
            "allgather_partitions": true,
            "allgather_bucket_size": 5e8,
            "reduce_scatter": true,
            "reduce_bucket_size": 5e8,
            "overlap_comm": true,
            "contiguous_gradients": true
        }
    },
    "rdzv_backend": "static",
    "same_network": true,
    "tpu_use_cluster": false,
    "tpu_use_sudo": false,
    "use_cpu": false
}
