data:
  root_dir: './data/vox1_png'
  sample_size:  [512, 512]
  sample_stride: 4
  sample_n_frames: 16
  id_sampling: True

solver:
  gradient_accumulation_steps: 1
  mixed_precision: fp16  # AMP용
  fp16_mode: True        # FP16-only 모드 여부
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False 
  max_train_steps: 100000
  max_grad_norm: 1.0
  num_repeats: 75

  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000
  validation_steps_tuple: [1, 10, 50, 100, 200, 500]

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: './pretrained_model/stable-diffusion-v1-5'
vae_model_path: './pretrained_model/sd-vae-ft-mse'
image_encoder_path: './pretrained_model/image_encoder'
lia_model_path: './pretrained_model/vox.pt'

train_bs: 16

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 

seed: 12580
resume_from_checkpoint: ''      # latest
checkpointing_steps: 4000
save_model_epoch_interval: 5
exp_name: 'stage1'
output_dir: './exp_output'